### ISSUE TITLE
RS dungeons don't seem to spawn

### ISSUE THREAD

**Issue by Mephodio** [TelepathicGrunt/RepurposedStructures-Fabric#210]
I used another mod to highlight all spawners around me and I couldn't find any RS dungeons. So maybe wells also don't work, I can't check easily.
I tried to increase their count using datapack, no result.
There are no related errors in log.

Tested versions: 6.0.1+1.19 and 6.0.2+1.19.

**Comment by TelepathicGrunt** [comment]
Should be fixed in v6.0.3 now. Thank you for letting me know!

**Comment by Mephodio** [comment]
Most dungeons work now, but ocean ones are still not spawning, even with increased chance.

**Comment by TelepathicGrunt** [comment]
Should be fixed now in v6.0.4

**Comment by Mephodio** [comment]
It works, thanks!
